# Generated by Django 3.0.4 on 2020-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_attractions/tourist_attractions_photos'),
        ),
    ]
