# Generated by Django 3.0.4 on 2020-03-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0003_auto_20200322_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_attractions'),
        ),
    ]
