# Generated by Django 3.0.4 on 2020-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0004_auto_20200322_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='cafllpcqge', editable=False, max_length=10),
        ),
    ]
