# Generated by Django 3.0.4 on 2020-03-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0007_auto_20200324_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='rfhytralvx', editable=False, max_length=10),
        ),
    ]
