# Generated by Django 3.0.4 on 2020-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0009_auto_20200326_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='eafmzrazgu', editable=False, max_length=10),
        ),
    ]
