# Generated by Django 3.0.4 on 2020-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0012_auto_20200326_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='jqqgutthjw', editable=False, max_length=10),
        ),
    ]
