# Generated by Django 3.0.4 on 2020-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0014_auto_20200326_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='mmgimtsaho', editable=False, max_length=10),
        ),
    ]
