# Generated by Django 3.0.4 on 2020-03-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0017_auto_20200326_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='usiivkmmnw', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='id_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourist_attractions.IdentificationDocument'),
        ),
    ]
