# Generated by Django 3.0.4 on 2020-03-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0018_auto_20200327_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='guid',
            field=models.CharField(default='ygpbiuyarm', editable=False, max_length=10),
        ),
    ]
