# Generated by Django 3.0.4 on 2020-03-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20200322_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shows'),
        ),
    ]
