# Generated by Django 3.0.4 on 2020-03-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='min_agr',
            new_name='min_age',
        ),
    ]
