# Generated by Django 3.0.4 on 2020-03-22 05:41

from django.db import migrations, models
import django.db.models.deletion
import tourist_attractions.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('guid', models.CharField(default=tourist_attractions.models.randomString, editable=False, max_length=10)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.Address')),
                ('shows', models.ManyToManyField(to='shows.Show')),
            ],
        ),
    ]
